name: Java CI with Maven

# 只要你往 main 分支推送代码，就触发这个任务
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    # 使用最新的 Linux 环境运行
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 第一步：把你的代码下载到服务器上

      - name: Set up JDK 21
        uses: actions/setup-java@v4 # 第二步：在服务器上安装 JDK 21
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml # 第三步：尝试编译并打包你的项目